.Net 8 - Build script fix
zarunbal/LogExpert pull request #300
Opened 2024-12-30 01:46 UTC by RandallFlagg

2025-01-01 19:56 UTC, RandallFlagg commented
@zarunbal hi,
Can you please help me solve the issue in the build? I don't know what causes the error and I don't have access to the terminal.

2025-01-03 15:02 UTC, Hirogen commented
> @zarunbal @Hirogen Hi all, Can you please help me solve the issues in the tests? I don't have access to the terminal which makes it more difficult to solve the problems.

I have a look

2025-01-03 16:35 UTC, Hirogen commented
it seems there is a problem with the columnizerlib, probably the csvColumnizer cannot find the source dll, seems a missing package or something, gonna investigate this on sunday

2025-01-03 16:36 UTC, Hirogen commented
you can test easily by using the commandline in the build folder => Build-ReleasePack.ps1 or Build-DebugPack.ps1 no need to upload changes to github

2025-01-04 14:57 UTC, Hirogen commented
the problem is, that the folder structure is no longer correct, somehow nuget trys to find the columnizerlib.dll in the src\bin\ folder but it is build into the "solution\bin" folder, just need to find why this is happening

2025-01-05 10:51 UTC, Hirogen commented
Problem seems to be one of the nuget packages, after updating to the latest it does no longer work

2025-01-05 11:26 UTC, Hirogen commented
I found the source code that is the problem

its in the _build.cs at line 299

```c#
    Target ColumnizerLibCreateNuget => _ => _
        .DependsOn(Compile, Test)
        .Executes(() =>
        {
            var columnizerFolder = SourceDirectory / "ColumnizerLib";

            NuGetTasks.NuGetPack(s =>
            {
                s = s.SetTargetPath(columnizerFolder / "ColumnizerLib.csproj")
                    //.DisableBuild()
                    .SetConfiguration(Configuration)
                    .SetProperty("version", VersionString)
                    .SetOutputDirectory(BinDirectory);
                return s;
            });
        });
```

2025-01-05 14:56 UTC, Hirogen requested changes
Finished review, please look at the comments

2025-01-05 14:56 UTC, Hirogen commented on src/LogExpert/Classes/Log/LogfileReader.cs
> +            const int WAIT_TIME = 10000;
Whats the reasoning behind this change, that would be a increase by a factor of 1000

2025-01-05 14:56 UTC, Hirogen commented on src/LogExpert/Classes/Log/LogfileReader.cs
> +                Console.WriteLine("else");
It seems that the Console.WriteLine is for debug purposes, this should be deleted in the last commit!

2025-01-05 14:56 UTC, Hirogen commented on src/ColumnizerLib/ColumnizerLib.csproj
> -    <OutputPath>..\..\bin\Release\</OutputPath>
I think here lies the problem, removal of the output path,  created a "default" path, that is currently unreachable, please add these in every project again

2025-01-05 14:56 UTC, Hirogen commented on src/LogExpert.Tests/DateFormatParserTest.cs
> +                if (culture.Name == "dz" || culture.Name == "ar" ||  culture.Name.StartsWith("ar-") || culture.Name.StartsWith("dz-"))
ar is arabic? 
please adapt the console message, so this is reflected as well

2025-01-05 14:56 UTC, Hirogen commented on src/WinFormsUI/Docking/DockPane.cs
> -        [SecurityPermission(SecurityAction.LinkDemand, Flags = SecurityPermissionFlag.UnmanagedCode)]
Whats the reasoning behind removing this warning? It still unmanaged code and might lead to problems?

2025-01-05 14:56 UTC, Hirogen commented on src/WinFormsUI/Docking/DockPaneStripBase.cs
> -        [SecurityPermission(SecurityAction.LinkDemand, Flags = SecurityPermissionFlag.UnmanagedCode)]
Whats the reasoning behind removing this warning? It still unmanaged code and might lead to problems?

2025-01-05 14:56 UTC, Hirogen commented on src/WinFormsUI/Docking/FloatWindow.cs
> -        [SecurityPermission(SecurityAction.LinkDemand, Flags = SecurityPermissionFlag.UnmanagedCode)]
Whats the reasoning behind removing this warning? It still unmanaged code and might lead to problems?

2025-01-05 14:56 UTC, Hirogen commented on src/WinFormsUI/Docking/DockPaneCaptionBase.cs
> -        [SecurityPermission(SecurityAction.LinkDemand, Flags = SecurityPermissionFlag.UnmanagedCode)]
Whats the reasoning behind removing this warning? It still unmanaged code and might lead to problems?

2025-01-05 15:15 UTC, TheNicker commented on src/LogExpert/Classes/Log/LogfileReader.cs
> +            const int WAIT_TIME = 10000;
Outdated, irrelevant

2025-01-05 15:21 UTC, RandallFlagg commented on src/WinFormsUI/Docking/DockPane.cs
> -        [SecurityPermission(SecurityAction.LinkDemand, Flags = SecurityPermissionFlag.UnmanagedCode)]
https://learn.microsoft.com/en-us/dotnet/api/system.security.permissions.securitypermission?view=windowsdesktop-9.0&viewFallbackFrom=net-9.0&form=MG0AV3

2025-01-05 15:21 UTC, RandallFlagg commented on src/WinFormsUI/Docking/DockPaneStripBase.cs
> -        [SecurityPermission(SecurityAction.LinkDemand, Flags = SecurityPermissionFlag.UnmanagedCode)]
https://learn.microsoft.com/en-us/dotnet/api/system.security.permissions.securitypermission?view=windowsdesktop-9.0&viewFallbackFrom=net-9.0&form=MG0AV3

2025-01-05 15:21 UTC, RandallFlagg commented on src/WinFormsUI/Docking/FloatWindow.cs
> -        [SecurityPermission(SecurityAction.LinkDemand, Flags = SecurityPermissionFlag.UnmanagedCode)]
https://learn.microsoft.com/en-us/dotnet/api/system.security.permissions.securitypermission?view=windowsdesktop-9.0&viewFallbackFrom=net-9.0&form=MG0AV3

2025-01-05 15:21 UTC, RandallFlagg commented on src/WinFormsUI/Docking/DockPaneCaptionBase.cs
> -        [SecurityPermission(SecurityAction.LinkDemand, Flags = SecurityPermissionFlag.UnmanagedCode)]
https://learn.microsoft.com/en-us/dotnet/api/system.security.permissions.securitypermission?view=windowsdesktop-9.0&viewFallbackFrom=net-9.0&form=MG0AV3

2025-01-05 15:25 UTC, RandallFlagg commented on src/ColumnizerLib/ColumnizerLib.csproj
> -    <OutputPath>..\..\bin\Release\</OutputPath>
The output path wasn't removed. It was unified to support both debug and release with the condition. If you will look closely it has the same output path as you mentioned.

Here is the correct code:
**Line 11:** `<OutputPath>$(SolutionDir)..\bin\$(Configuration)</OutputPath>`

2025-01-05 18:07 UTC, RandallFlagg commented on src/LogExpert.Tests/DateFormatParserTest.cs
> +                if (culture.Name == "dz" || culture.Name == "ar" ||  culture.Name.StartsWith("ar-") || culture.Name.StartsWith("dz-"))
Done

2025-01-06 09:23 UTC, Hirogen approved these changes

2025-01-06 09:23 UTC, Hirogen commented
thanks for the contribution!

2025-01-06 09:23 UTC, merged